name: Deploy to ECR

on: 
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: clo835-assignment1
        IMAGE_TAG1: v1.1
        IMAGE_TAG2: v2.1
        
      run: |
        cd cats/
        ls -ltra
        # Docker build cat
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1 .
        # Unit test
        docker run -d -p 80:80 --name nodeappcat $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        curl localhost -vvv
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1
        cd ../dogs/
        ls -ltra
        # Docker build dogs
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2 .
        # Unit test
        docker run -d --name nodeappdog $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        curl localhost -vvv
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2
